### ISSUE TITLE
aiozipkin 0.5.0 does not work with python 3.5.3 and aiohttp >= 3.0 , < 3.1

### ISSUE THREAD

**Issue by rodnsi** [aio-libs/aiozipkin#264]
Hello,
1. `aiozipkin 0.5.0` does not work with `python 3.5.3` and `aiohttp >= 3.0 , < 3.1`.
Indeed, my tests failed with: `cannot import name 'AsyncContextManager'`. So, `python 3.5.4` is required because `typing.AsyncGenerator is new in python 3.5.4` (https://docs.python.org/3.5/library/typing.html#typing.AsyncGenerator)

```
...
[2020-05-19T08:46:37.878Z] ______________ ERROR collecting xxx/tests/test_xxx.py ______________
[2020-05-19T08:46:37.878Z] ImportError while importing test module 'xxx/tests/test_xxx.py'.
[2020-05-19T08:46:37.878Z] Hint: make sure your test modules/packages have valid Python names.
[2020-05-19T08:46:37.878Z] Traceback:
[2020-05-19T08:46:37.878Z] xxx/tests/__init__.py:16: in <module>
[2020-05-19T08:46:37.878Z]     from xxx.bin.api import init_webapp  # noqa
[2020-05-19T08:46:37.878Z] xxx/bin/api.py:8: in <module>
[2020-05-19T08:46:37.878Z]     import aiozipkin
[2020-05-19T08:46:37.878Z] .pyenv-python3.5/lib/python3.5/site-packages/aiozipkin/__init__.py:1: in <module>
[2020-05-19T08:46:37.878Z]     from .aiohttp_helpers import (
[2020-05-19T08:46:37.878Z] .pyenv-python3.5/lib/python3.5/site-packages/aiozipkin/aiohttp_helpers.py:15: in <module>
[2020-05-19T08:46:37.878Z]     from .tracer import Tracer
[2020-05-19T08:46:37.878Z] .pyenv-python3.5/lib/python3.5/site-packages/aiozipkin/tracer.py:1: in <module>
[2020-05-19T08:46:37.878Z]     from typing import Optional, Dict, Awaitable, Any, AsyncContextManager, cast, TYPE_CHECKING  # flake8: noqa
[2020-05-19T08:46:37.878Z] E   ImportError: cannot import name 'AsyncContextManager'
...
```

2. Contrary to what is mentioned in your README file, aiozipkin is not a python 3.5+ module
```
aiozipkin is Python 3.5+ module ...
```

Can you update your documentation please?

Best regards,
rodnsi

**Comment by asvetlov** [comment]
Thanks for the report.
In fact, the library is Python 3.6+ compatible.
